version: "3.9"

services:
  bot:
    build: .
    container_name: tg-bot
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_DATABASE: ${NEO4J_DATABASE}

    restart: unless-stopped

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "18080:7474"   # веб-интерфейс Neo4j на хосте
      - "7687:7687"    # bolt (тут нет конфликтов, 7687 вне исключений)

    environment:
      NEO4J_AUTH: neo4j/12345678
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:7474" ]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped
