version: "3.9"

services:
  bot:
    build: .
    container_name: tg-bot
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: 12345678
      NEO4J_DATABASE: neo4j

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # web-интерфейс Neo4j Browser
      - "7687:7687"   # bolt-соединение
    environment:
      NEO4J_AUTH: neo4j/12345678
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
